env:
  browser: true
  es6: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
  mdtoast: readonly
  confirm: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: babel-eslint
settings:
  import/resolver: webpack
plugins:
  - react
rules:
  indent:
    - error
    - 2
    - ignoredNodes: #< "indent" and "react/jsx-indent" are conflicting rules, this is the workaround
      - JSXElement
      - 'JSXElement > *'
      - JSXAttribute
      - JSXIdentifier
      - JSXNamespacedName
      - JSXMemberExpression
      - JSXSpreadAttribute
      - JSXExpressionContainer
      - JSXOpeningElement
      - JSXClosingElement
      - JSXText
      - JSXEmptyExpression
      - JSXSpreadChild
  object-curly-newline:
    - error
    - ObjectExpression:
        minProperties: 6
        multiline: true
      ObjectPattern:
        minProperties: 6
        multiline: true
  "react/jsx-first-prop-new-line": [error, multiline]
  "react/jsx-filename-extension":
    - error
    - extensions: [".js", ".jsx"]
  "react/jsx-wrap-multilines":
    - error
    - logical: ignore
  "react/jsx-indent":
    - error
    - 2
    - indentLogicalExpressions: true
  "react/jsx-closing-tag-location": off
  "react/destructuring-assignment": off
  "no-alert": off
  "no-unused-expressions":
    - error
    - allowShortCircuit: true
      allowTernary: true
  "no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
  "import/no-named-default": off
  # TODO: enable after refactoring:
  "jsx-a11y/click-events-have-key-events": off
  "jsx-a11y/anchor-is-valid": off
  "react/forbid-prop-types": off
  "react/no-unused-state": off
  "jsx-a11y/label-has-for": off
  "react/require-default-props": off
  "global-require": off
  "no-use-before-define": off
  "no-restricted-globals": off
