env:
  browser: true
  es6: true
extends: airbnb
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
parser: babel-eslint
settings:
  import/resolver: webpack
plugins:
  - react
rules:
  indent:
    - error
    - 2
    - ignoredNodes: #< "indent" and "react/jsx-indent" are conflicting rules, this is the workaround
      - JSXElement
      - 'JSXElement > *'
      - JSXAttribute
      - JSXIdentifier
      - JSXNamespacedName
      - JSXMemberExpression
      - JSXSpreadAttribute
      - JSXExpressionContainer
      - JSXOpeningElement
      - JSXClosingElement
      - JSXText
      - JSXEmptyExpression
      - JSXSpreadChild
  object-curly-newline:
    - error
    - ObjectExpression:
        minProperties: 6
        multiline: true
      ObjectPattern:
        minProperties: 6
        multiline: true
  "react/jsx-first-prop-new-line": [1, multiline]
  "react/jsx-filename-extension": [1, { "extensions": [".js", ".jsx"] }]
  "react/jsx-wrap-multilines": [1, { "logical": "ignore" }]
  "react/jsx-indent":
    - error
    - 2
    - indentLogicalExpressions: true
  "react/jsx-closing-tag-location": [0]
  # TODO: enable after refactoring:
  "jsx-a11y/click-events-have-key-events": [0]
  "jsx-a11y/anchor-is-valid": [0]
  "react/forbid-prop-types": [0]
  "react/no-unused-state": "off"
  "jsx-a11y/label-has-for": "off"
  "react/require-default-props": "off"
  "global-require": "off"
