# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 9c9959770d48e313162d5be6c19d3b7136718e175db39f8405402217da6792ba3f6963e4f298f63b74fa7cd1b6aaaebaeff74b084579cc755399948cb7af9484

test:
  secret_key_base: e7b1621e8af54814caf82298b70f80e7a4684d33ad28ab64acdc5f489a515cdd0789641efdb29851394fb11aa3b4d053388400dd4199c96fb18cba73a348bd3e

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
