const acts = {
  LOAD_POST_CARDS_REQUEST: 'LOAD_POST_CARDS_REQUEST_V1',
  LOAD_POST_CARDS_FAILED: 'LOAD_POST_CARDS_FAILED_V1',
  LOAD_POST_CARDS_SUCCESS: 'LOAD_POST_CARDS_SUCCESS_V1',
};

export default acts;
