source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

# For same_site: :none :
gem 'rack', git: 'https://github.com/bitia-ru/rack.git', branch: '2.0.6-samesite'

gem 'jbuilder', '~> 2.5'
gem 'pg'
gem 'puma', '~> 3.11'
gem 'rails', '~> 5.2.1'
gem 'redis', '~> 4.0'
gem 'responders'

# Speeds up boot, required in config/boot.rb
gem 'bootsnap', '>= 1.1.0', require: false

gem 'rack-cors'

group :development, :test do
  gem 'pry'
end

group :development do
  gem 'listen', '>= 3.0.5', '< 3.2'
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

gem 'sidekiq'

gem 'config'

gem 'mail'

gem 'warden'

gem 'pundit'

gem 'bcrypt'

gem 'sentry-raven'

gem 'google-cloud-storage'

gem 'image_processing', '~> 1.2'

gem 'redis-rails'
