const acts = {
  LOAD_USER_SESSION_REQUEST: 'LOAD_USER_SESSION_REQUEST_V1',
  LOAD_USER_SESSION_FAILED: 'LOAD_USER_SESSION_FAILED_V1',
  LOAD_USER_SESSION_SUCCESS: 'LOAD_USER_SESSION_SUCCESS_V1',
};

export default acts;
