const acts = {
  LOAD_USERS_REQUEST: 'LOAD_USERS_REQUEST_V1',
  LOAD_USERS_FAILED: 'LOAD_USER_FAILED_V1',
  LOAD_USERS_SUCCESS: 'LOAD_USERS_SUCCESS_V1',
  LOAD_USERS: 'LOAD_USERS_V1',
};

export default acts;
