const acts = {
  LOAD_TAGS_REQUEST: 'LOAD_TAGS_REQUEST_V1',
  LOAD_TAGS_FAILED: 'LOAD_TAGS_FAILED_V1',
  LOAD_TAGS_SUCCESS: 'LOAD_TAGS_SUCCESS_V1',
  REMOVE_TAG_SUCCESS: 'REMOVE_TAG_SUCCESS_V1',
};

export default acts;
