const acts = {
  LOAD_COMMENTS_REQUEST: 'LOAD_COMMENTS_REQUEST_V1',
  LOAD_COMMENTS_FAILED: 'LOAD_COMMENTS_FAILED_V1',
  LOAD_COMMENTS_SUCCESS: 'LOAD_COMMENTS_SUCCESS_V1',
  REMOVE_COMMENT_SUCCESS: 'REMOVE_COMMENT_SUCCESS_V1',
};

export default acts;
