#!/bin/bash

set -e
set -u

BRANCH_NAME=${1}
FRONTEND_NAME=$(basename $BRANCH_NAME)

mkdir -p ./${FRONTEND_NAME}
rm -rf ./${FRONTEND_NAME}/{*,.*} || true

git fetch

git archive --format=tar origin/${BRANCH_NAME} ./frontend | \
  tar -xv --strip-components=1 -C ./${FRONTEND_NAME} -f -

python3 scripts/private/frontends-add.py ${FRONTEND_NAME}

echo "Frontend ${FRONTEND_NAME} added."

./dc build ${FRONTEND_NAME,,} gw
./dc up -d

