const acts = {
  LOAD_POSTS_REQUEST: 'LOAD_POSTS_REQUEST_V1',
  LOAD_POSTS_FAILED: 'LOAD_POSTS_FAILED_V1',
  LOAD_POSTS_SUCCESS: 'LOAD_POSTS_SUCCESS_V1',
  REMOVE_POST_SUCCESS: 'REMOVE_POST_SUCCESS_V1',
  LOAD_POST_COMMENTS_SUCCESS: 'LOAD_POST_COMMENTS_SUCCESS_V1',
  CREATE_COMMENT_SUCCESS: 'CREATE_COMMENT_SUCCESS_V1',
  UPDATE_COMMENT_SUCCESS: 'UPDATE_COMMENT_SUCCESS_V1',
  REMOVE_COMMENT_SUCCESS: 'REMOVE_COMMENT_SUCCESS_V1',
};

export default acts;
