name: "Run tests and checks"
on: push

jobs:
  ci:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Preparations
        run: |
          cp frontend/Dockerfile{.ci,}
      - uses: ./.github/actions/backend-ci
